site_name: Nixware API
nav:
  - 'home': 'index.md'
  - 'render.md'
  - 'menu':
    - 'home': 'menu/index.md'
    - 'types':
      - 'check_box_t': 'menu/types/check_box_t.md'
      - 'slider_int_t': 'menu/types/slider_int_t.md'
      - 'slider_float_t': 'menu/types/slider_float_t.md'
      - 'combo_box_t': 'menu/types/combo_box_t.md'
      - 'multi_combo_box_t': 'menu/types/multi_combo_box_t.md'
      - 'key_bind_t': 'menu/types/key_bind_t.md'
      - 'color_picker_t': 'menu/types/color_picker_t.md'
  - 'globals.md'
  - 'types':
    - 'vec2_t': 'types/vec2_t.md'
    - 'vec3_t': 'types/vec3_t.md'
    - 'color_t': 'types/color_t.md'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    - navigation.expand
    - navigation.prune
    - navigation.top
    - content.code.copy
  palette:
    primary: darkgrey
    scheme: slate
markdown_extensions:
  - toc:
      title: On this page
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
plugins:
  - macros
watch:
  - main.py